config/routes.rb
Caillou::Application.routes.draw do
  resources :contacts

  get '/home', to: 'home#show'
  get '/services', to: 'services#show'
  get '/whowe', to: 'whowe#show'
  get '/partners', to: 'partners#show'

  root :to => "home#show"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Thank you for contacting us.' }
        format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :subject, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end 
  def create
    redirect_to new_home_path
  end
  def index
    redirect_to new_home_path
  end
  def new 
  end 
  def invalid_page
    redirect_to new_home_path
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  def show
  end 
  def create
    redirect_to show_partner_path
  end
  def index
    redirect_to show_partner_path
  end
  def invalid_page
    redirect_to show_partner_path
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def show
  end 
  def create
    redirect_to show_service_path
  end
  def index
    redirect_to show_service_path
  end
  def invalid_page
    redirect_to show_service_path
  end
end

app/controllers/whowe_controller.rb
class WhoweController < ApplicationController
  def show
  end 
  def create
    redirect_to show_whowe_path
  end
  def index
    redirect_to show_whowe_path
  end
  def invalid_page
    redirect_to show_whowe_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.haml
= form_for(@contact) do |f|
  - if @contact.errors.any?
    #error_explanation
      %h2
        = pluralize(@contact.errors.count, "error")
        prohibited this contact from being saved:
      %ul
        - @contact.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :subject
    %br/
    = f.text_field :subject
  .field
    = f.label :message
    %br/
    = f.text_field :message
  .actions
    = f.submit

app/views/contacts/edit.html.haml
%h1 Editing contact
= render 'form'
= link_to 'Show', @contact
|
\#{link_to 'Back', contacts_path}

app/views/contacts/index.html.haml
%h1 Listing contacts
%table
  %thead
    %tr
      %th Name
      %th Email
      %th Subject
      %th Message
      %th
      %th
      %th
  %tbody
    - @contacts.each do |contact|
      %tr
        %td= contact.name
        %td= contact.email
        %td= contact.subject
        %td= contact.message
        %td= link_to 'Show', contact
        %td= link_to 'Edit', edit_contact_path(contact)
        %td= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Contact', new_contact_path

app/views/contacts/new.html.haml
%h1 Contact Us 
= render 'form'

app/views/contacts/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @contact.name
%p
  %strong Email:
  = @contact.email
%p
  %strong Subject:
  = @contact.subject
%p
  %strong Message:
  = @contact.message
= link_to 'Edit', edit_contact_path(@contact)
|
\#{link_to 'Back', contacts_path}

app/views/home/show.html.haml
%h1 Home
.span5
  %img{:src => "http://www.chicagoarchitecture.info/CAI/Images/201108/UnitrinBuilding-Chicago-00907-005a.jpg"}

.span4
  Vestibulum imperdiet, ligula non sagittis feugiat, leo sem pretium dui, ac gravida nisl erat rutrum lectus. Ut viverra ipsum eu risus pulvinar, ac auctor enim consequat. Pellentesque semper ultricies nisi non scelerisque. Quisque pretium mauris at dolor feugiat euismod. Nullam a molestie ante. Suspendisse commodo nibh neque, ut interdum mi molestie eget.
  Donec in sapien elit. Maecenas placerat magna at dolor faucibus rhoncus. Curabitur suscipit sapien dapibus mauris tincidunt, quis porta felis lacinia. Cras vehicula nec nibh eu vehicula. Donec facilisis eros mattis egestas convallis. Sed porttitor gravida tortor. Integer vitae nisl suscipit, lobortis turpis at, gravida nibh. Mauris pellentesque, odio eu tincidunt pharetra, leo urna pulvinar quam, a tempor erat ante ac est. Nam eros orci, vulputate non mollis at, facilisis nec leo.

Faucibus sed justo mollis semper. Donec lacinia est massa, ut egestas lectus vulputate sed. Ut tempor elit malesuada leo adipiscing, nec consequat tellus rutrum. Nam at sollicitudin nulla, eu bibendum enim. Aliquam condimentum aliquet ante eget mollis. Donec vel vulputate tortor. Cras commodo ac diam ac pharetra. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean vulputate erat quam, non pulvinar felis semper in. Sed ultricies gravida porta. Ut non porttitor sapien, ac convallis urna. Vivamus mauris lacus, vehicula vel hendrerit at, tempor convallis metus. Nullam lacinia eleifend suscipit. Nullam imperdiet luctus pretium. Ut egestas, sem id bibendum pellentesque, sapien neque sagittis mauris, vitae auctor nisi lorem vitae erat. Vestibulum tempus vestibulum purus, vel tempor magna egestas quis.

Suspendisse rhoncus ornare dictum. Cras in magna ac orci vehicula interdum. Fusce placerat tincidunt velit a egestas. Vestibulum imperdiet, ligula non sagittis feugiat, leo sem pretium dui, ac gravida nisl erat rutrum lectus. Ut viverra ipsum eu risus pulvinar, ac auctor enim consequat. Pellentesque semper ultricies nisi non scelerisque. Quisque pretium mauris at dolor feugiat euismod. Nullam a molestie ante. Suspendisse commodo nibh neque, ut interdum mi molestie eget. Vestibulum fermentum eros a elit suscipit molestie sed eget felis. Pellentesque mattis varius justo at dictum. Quisque porttitor egestas felis eu semper.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Caillou
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        %a.brand{href: "#"} Caillou 
        .nav-collapse
          %ul.nav
            %li= link_to "Home", home_path
            %li= link_to "Who we", whowe_path
            %li= link_to "Our Services", services_path
            %li= link_to "Partner Us", partners_path
            %li= link_to "Contact Us", contacts_path
    .container
      .row
        .span9
          = yield
        .span3
          %h2
            About Us
        Sed faucibus sed justo mollis semper. Donec lacinia est massa, ut egestas lectus vulputate sed. Ut tempor elit malesuada leo adipiscing, nec consequat tellus rutrum. Nam at sollicitudin nulla, eu bibendum enim. Aliquam condimentum aliquet ante eget mollis. Donec vel vulputate tortor. Cras commodo ac diam ac pharetra. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean vulputate erat quam, non pulvinar felis semper in. Sed ultricies gravida porta. Ut non porttitor sapien, ac convallis urna. Vivamus mauris lacus, vehicula vel hendrerit at, tempor convallis metus. Nullam lacinia eleifend suscipit. Nullam imperdiet luctus pretium. Ut egestas, sem id bibendum pellentesque, sapien neque sagittis mauris, vitae auctor nisi lorem vitae erat. Vestibulum tempus vestibulum purus, vel tempor magna egestas quis. 

app/views/partners/show.html.haml
%h1 Partners 
.row
  .span6
    %img{:src => "https://www.google.com/images/srpr/logo11w.png"}
  .span4
  Vestibulum imperdiet, ligula non sagittis feugiat, leo sem pretium dui, ac gravida nisl erat rutrum lectus. Ut viverra ipsum eu risus pulvinar, ac auctor enim consequat. Pellentesque semper ultricies nisi non scelerisque. Quisque pretium mauris at dolor feugiat euismod. Nullam a molestie ante. Suspendisse commodo nibh neque, ut interdum mi molestie eget. Pellentesque semper ultricies nisi non scelerisque. Quisque pretium mauris at dolor feugiat euismod. Nullam a molestie ante. Suspendisse commodo nibh neque, ut interdum mi molestie eget. Pellentesque semper ultricies nisi non scelerisque. Quisque pretium mauris at dolor feugiat euismod. Nullam a molestie ante. Suspendisse commodo nibh neque, ut interdum mi molestie eget.
 
.row 
  .span6
    %img{:src => "http://c.s-microsoft.com/en-us/CMSImages/Win81_Meet_1018_420x210_EN_US.jpg?version=4d6af70d-acc9-4209-d4cf-de33e88a3a0d"}
  .span4
  Vestibulum imperdiet, ligula non sagittis feugiat, leo sem pretium dui, ac gravida nisl erat rutrum lectus. Ut viverra ipsum eu risus pulvinar, ac auctor enim consequat. Pellentesque semper ultricies nisi non scelerisque. Quisque pretium mauris at dolor feugiat euismod. Nullam a molestie ante. Suspendisse commodo nibh neque, ut interdum mi molestie eget.
  Pellentesque semper ultricies nisi non scelerisque. Quisque pretium mauris at dolor feugiat euismod. Nullam a molestie ante. Suspendisse commodo nibh neque, ut interdum mi molestie eget. Pellentesque semper ultricies nisi non scelerisque. Quisque pretium mauris at dolor feugiat euismod. Nullam a molestie ante. Suspendisse commodo nibh neque, ut interdum mi molestie eget.
 
 

.row 
  .span6
    %img{:src => "http://c.s-microsoft.com/en-us/CMSImages/mslogo.png?version=856673f8-e6be-0476-6669-d5bf2300391d"}
  .span4
  Vestibulum imperdiet, ligula non sagittis feugiat, leo sem pretium dui, ac gravida nisl erat rutrum lectus. Ut viverra ipsum eu risus pulvinar, ac auctor enim consequat. Pellentesque semper ultricies nisi non scelerisque. Quisque pretium mauris at dolor feugiat euismod. Nullam a molestie ante. Suspendisse commodo nibh neque, ut interdum mi molestie eget. Pellentesque semper ultricies nisi non scelerisque. Quisque pretium mauris at dolor feugiat euismod. Nullam a molestie ante. Suspendisse commodo nibh neque, ut interdum mi molestie eget.
 

app/views/services/show.html.haml
%h1 Services
.span5
  %img{:src => "http://www.chicagoarchitecture.info/CAI/Images/201108/UnitrinBuilding-Chicago-00907-001a.jpg"}

app/views/whowe/show.html.haml
%h1 Who We
.span6
  %img{:src => "http://blog.chicagoarchitecture.info/wp-content/uploads/2012/08/8.jpg"}

.span4
  Vestibulum imperdiet, ligula non sagittis feugiat, leo sem pretium dui, ac gravida nisl erat rutrum lectus. Ut viverra ipsum eu risus pulvinar, ac auctor enim consequat. Pellentesque semper ultricies nisi non scelerisque. Quisque pretium mauris at dolor feugiat euismod. Nullam a molestie ante. Suspendisse commodo nibh neque, ut interdum mi molestie eget.
 